<h1>trainning Pipleline</h1>

In [ ]:
import numpy as np
from numpy import nan
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [2]:
data1 = pd.read_csv("train.csv")

In [3]:
data1.sample(6)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
175,176,20,RL,84.0,12615,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2007,WD,Normal,243000
1224,1225,60,RL,60.0,15384,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,184000
733,734,20,RL,80.0,10000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdWo,Shed,400,3,2009,WD,Normal,131400
339,340,20,RL,66.0,12400,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2009,WD,Normal,155000
1027,1028,20,RL,71.0,9520,Pave,NaN,IR1,HLS,AllPub,...,0,NaN,NaN,NaN,0,4,2008,New,Partial,293077
281,282,20,FV,60.0,7200,Pave,Pave,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,New,Partial,185000

In [4]:
import sys
sys.path.append(r'C:\Users\goldu\Downloads\pw2')
sys.path.append(r'C:\Users\goldu\Downloads\pw2\app')
#sys.path.append('../')
#sys.path.append('../app')
sys.path

['C:\\Users\\goldu\\Downloads',
 'C:\\Users\\goldu\\anaconda3\\python38.zip',
 'C:\\Users\\goldu\\anaconda3\\DLLs',
 'C:\\Users\\goldu\\anaconda3\\lib',
 'C:\\Users\\goldu\\anaconda3',
 '',
 'C:\\Users\\goldu\\anaconda3\\lib\\site-packages',
 'C:\\Users\\goldu\\anaconda3\\lib\\site-packages\\locket-0.2.1-py3.8.egg',
 'C:\\Users\\goldu\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\goldu\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\goldu\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\goldu\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\goldu\\.ipython',
 'C:\\Users\\goldu\\Downloads\\pw2',
 'C:\\Users\\goldu\\Downloads\\pw2\\app']

In [5]:
from app.model_trainning import model_training
rsme = model_training( data1 )
print(rsme)

Coefficients:  210.90841402924033
Intercept:  159197.10897501098
Root mean square error (RMSE): 71669.92
71669.91953186125

<h2>Test Pipleline</h2>

In [6]:
data = pd.read_csv("test.csv")

In [7]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [9]:
from app.inference import prediction
pred = prediction( data)
print( pred)

[[159197.10897501]
 [181975.21769017]
 [159197.10897501]
 ...
 [159197.10897501]
 [159197.10897501]
 [179022.49989376]]